services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: root123
    ports:
      - "8080:80"
    networks:
      - postgres-network

networks:
  postgres-network:
    external: true
